import { access, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import chalk from "chalk";
import { DEFAULT_CONFIG_YAML } from "../config/defaults.ts";
import { writeFileAtomic } from "../generation/file-writer.ts";
import { DEFAULT_RULE_TEMPLATES } from "../lint/default-rules.ts";
import { generateTokens } from "./gen.ts";

// ============================================================================
// Error Types
// ============================================================================

export class InitError extends Error {
  constructor(
    message: string,
    public readonly cause?: unknown
  ) {
    super(message);
    this.name = "InitError";
  }
}

// ============================================================================
// Directory Structure
// ============================================================================

const NORTH_DIR = "north";
const TOKENS_DIR = "north/tokens";
const RULES_DIR = "north/rules";
const CONFIG_FILE = "north/north.config.yaml";
const BASE_CSS_FILE = "north/tokens/base.css";

/**
 * Check if file or directory exists
 */
async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Create base.css template
 */
function createBaseCSSTemplate(): string {
  return `/**
 * North Base Tokens
 *
 * This file is for custom tokens that aren't generated by North.
 * Add your custom CSS variables, component styles, or overrides here.
 *
 * This file is NOT overwritten by 'north gen'.
 */

/* Custom tokens */
/* Add your custom --token: value; declarations here */

/* Component-specific tokens */
/* --card-padding: var(--spacing-lg); */
/* --button-radius: var(--radius-md); */
`;
}

// ============================================================================
// Init Command
// ============================================================================

export interface InitOptions {
  cwd?: string;
  force?: boolean;
}

export interface InitResult {
  success: boolean;
  message: string;
  error?: Error;
}

/**
 * Initialize North in the current project
 */
export async function init(options: InitOptions = {}): Promise<InitResult> {
  const cwd = options.cwd ?? process.cwd();
  const northDir = resolve(cwd, NORTH_DIR);
  const tokensDir = resolve(cwd, TOKENS_DIR);
  const rulesDir = resolve(cwd, RULES_DIR);
  const configFile = resolve(cwd, CONFIG_FILE);
  const baseCSSFile = resolve(cwd, BASE_CSS_FILE);

  try {
    // Check if already initialized
    const alreadyInitialized = await exists(configFile);

    if (alreadyInitialized && !options.force) {
      console.log(chalk.yellow("⚠ North is already initialized"));
      console.log(chalk.dim(`Config file exists: ${CONFIG_FILE}`));
      console.log(
        chalk.dim("\nTo reinitialize, run: north init --force (this will overwrite existing files)")
      );

      return {
        success: true,
        message: "Already initialized",
      };
    }

    console.log(chalk.bold("Initializing North...\n"));

    // Create directory structure
    console.log(chalk.dim("Creating directories..."));
    await mkdir(northDir, { recursive: true });
    await mkdir(tokensDir, { recursive: true });
    await mkdir(rulesDir, { recursive: true });
    console.log(`${chalk.green("✓")} Created north/ directory`);
    console.log(`${chalk.green("✓")} Created north/tokens/ directory`);
    console.log(`${chalk.green("✓")} Created north/rules/ directory`);

    // Write config file
    console.log(chalk.dim("\nWriting configuration..."));
    await writeFileAtomic(configFile, DEFAULT_CONFIG_YAML);
    console.log(`${chalk.green("✓")} Created ${CONFIG_FILE}`);

    // Write base.css (only if it doesn't exist or force mode)
    const baseCSSExists = await exists(baseCSSFile);
    if (!baseCSSExists || options.force) {
      await writeFileAtomic(baseCSSFile, createBaseCSSTemplate());
      console.log(`${chalk.green("✓")} Created ${BASE_CSS_FILE}`);
    } else {
      console.log(chalk.dim(`  Skipped ${BASE_CSS_FILE} (already exists)`));
    }

    // Write default lint rules
    console.log(chalk.dim("\nWriting lint rules..."));

    for (const template of DEFAULT_RULE_TEMPLATES) {
      const rulePath = resolve(rulesDir, template.filename);
      const ruleExists = await exists(rulePath);

      if (!ruleExists || options.force) {
        await writeFileAtomic(rulePath, template.content);
        console.log(`${chalk.green("✓")} Created ${RULES_DIR}/${template.filename}`);
      } else {
        console.log(chalk.dim(`  Skipped ${RULES_DIR}/${template.filename} (already exists)`));
      }
    }

    // Run initial generation
    console.log(chalk.dim("\nGenerating tokens..."));
    const genResult = await generateTokens({ cwd });

    if (!genResult.success) {
      console.log(`${chalk.red("✗")} Failed to generate tokens`);
      return {
        success: false,
        message: "Initialization incomplete",
        error: genResult.error,
      };
    }

    console.log(`${chalk.green("✓")} Generated tokens`);

    // Success message
    console.log(chalk.bold.green("\n✓ North initialized successfully!\n"));

    console.log("Next steps:");
    console.log(
      `${chalk.cyan("  1.")} Import tokens in your CSS: ${chalk.dim("@import './north/tokens/generated.css';")}`
    );
    console.log(
      `${chalk.cyan("  2.")} Customize your config: ${chalk.dim("north/north.config.yaml")}`
    );
    console.log(`${chalk.cyan("  3.")} Regenerate tokens: ${chalk.dim("north gen")}`);
    console.log(`${chalk.cyan("  4.")} Validate setup: ${chalk.dim("north doctor")}`);

    return {
      success: true,
      message: "Initialized successfully",
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);

    console.log(chalk.red("\n✗ Initialization failed"));
    console.log(chalk.dim(errorMessage));

    return {
      success: false,
      message: `Initialization failed: ${errorMessage}`,
      error: error instanceof Error ? error : new InitError(errorMessage),
    };
  }
}
